### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by natec425** [BaseCampCoding/unit-project-2-charles-and-jeremiah-t#1]
Please update your proposal to match the requested format.

Compare against the [Example Proposal](https://www.notion.so/bccastaff/Example-Project-Proposal-09d526fb857148929e97edc59b39e5b3) or [another group's proposal](https://github.com/BaseCampCoding/unit-project-2-kenia-and-gregory/blob/master/PROPOSAL.md) for inspiration.

**Comment by natec425** [comment]
## Daily Goals

Please update your proposal to include an outline of how you imagine the work will be split up on Wednesday and Thursday. What will @Charles-Mardis  work on? What will @jtatum2101  work on?

## How will you use the content from this unit?

You told me that you would use these things, but you didn't tell me how.

- Do you have an idea of what tables you might have?
- Do you have an idea of what classes you might have?

**Comment by natec425** [comment]
I looked up your prior art projects. This sounds like a neat idea, but I think we might need to be careful about how big of a bite you try to take. It might just be my lack of comfort with this area, but I feel like it would be easy to get lost in the weeds of cryptography and not give yourself the opportunity to show us that you can develop software. With that in mind, I suggest you reshape your project like this:

- You build a password manager (you can store your information in the database)
- You build a GUI for that password manager (you would use classes provided by Tkinter)
- You can add a "password strength check" tool that shows how long it took to crack your password with hashcat/john the ripper/etc.

Hopefully this helps scratch your ethical hacking itch while controlling the scope of your project.

How does this sound, @Charles-Mardis, @jtatum2101?

Do you have any thoughts @CoreyHollis?

**Comment by Charles-Mardis** [comment]
Hey Mr. Nate,
Jeremiah and I decided that would be a better project. We will go on that.
Sincerley,
Jeremiah and Charles
